include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/trivy.yml

stages:
  - versions
  - prebuild
  - verify
  - build
  - publish
  - containerize
  - scan
  - notify

versions:
  stage: versions
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
    PHP_MINORS: "4 3"
  before_script:
    - apk add --no-cache grep
  script:
    - |
      for minor in $PHP_MINORS; do
        wget -qO- https://www.php.net/downloads.php | grep -oP "(?<=>php-)([7]\.[${minor}]\.[0-9]{1,2})" | awk 'NR==1{print $1}' >> versions.txt
      done;
  artifacts:
    paths:
      - versions.txt
    expire_in: 3 hours
  tags:
    - jitesoft

gpg:import:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: prebuild
  before_script:
    - apk add --no-cache gnupg
  script:
    - |
      if [ -f keys.out ]; then
        gpg --import keys.out
      fi
    - |
      for key in `cat gpg-keys.txt`; do
        gpg --list-keys ${key} || (gpg --keyserver pgp.mit.edu --recv-keys "${key}" || gpg --keyserver keyserver.pgp.com --recv-keys "${key}" || gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "${key}")
      done
    - gpg --export > keys.out
  cache:
    key: php.gpg.keyring
    paths:
      - keys.out
  artifacts:
    paths:
      - keys.out
    expire_in: 3 hours
  tags:
    - jitesoft

download:
  stage: prebuild
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
  dependencies:
    - versions
  before_script:
    - apk add --no-cache curl
  script:
    - mkdir versions
    - |
      for version in `cat versions.txt`; do
        curl -L https://www.php.net/get/php-${version}.tar.xz/from/this/mirror -o versions/php-${version:0:3}.tar.xz;
        curl -L https://www.php.net/get/php-${version}.tar.xz.asc/from/this/mirror -o versions/php-${version:0:3}.tar.xz.asc;
      done;
  artifacts:
    paths:
      - versions/*.tar.xz
      - versions/*.tar.xz.asc
    expire_in: 1 day
  tags:
    - jitesoft

gpg:verify:
  variables:
    GIT_STRATEGY: none
  stage: verify
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  needs:
    - download
    - gpg:import
  before_script:
    - apk add --no-cache gnupg
    - gpg --import keys.out
  script:
    - for i in versions/*.tar.xz ; do gpg --verify ${i}.asc ${i} ; done
  tags:
    - jitesoft

.cross:build:shared: &shared
  image: registry.gitlab.com/jitesoft/dockerfiles/misc/buildbase:latest
  stage: build
  needs:
    - versions
    - gpg:verify
    - download
  before_script:
    - apk add --no-cache oniguruma-dev argon2-dev curl-dev libedit-dev libsodium-dev libxml2-dev openssl-dev sqlite-dev dpkg-dev
    - if [ ! -d "ccache" ]; then mkdir ccache; fi
    - export PATH="/usr/lib/ccache/bin:$PATH"
    - ccache -s
    - export CPPFLAGS="${CPPFLAGS} -fstack-protector-strong -fpic -fpie -O2"
    - export CFLAGS="${CFLAGS} -fstack-protector-strong -fpic -fpie -O2"
    - cp versions/php-${PHP_VERSION}.tar.xz php.tar.xz
    - mkdir src
    - tar -Jxhf php.tar.xz -C src/ --strip-components=1
    - addgroup -g 82 -S www-data && adduser -u 82 -D -S -G www-data www-data
  after_script:
    - ccache -s
    - rm -f /usr/local/bin/phpdbg
    - cp scripts/* /usr/local/bin/
    - $(cd /usr/local && tar -czf /tmp/php-${ARCH}-${PHP_VERSION}-${BUILD_TYPE}.tar.gz *)
    - mkdir binaries
    - mv /tmp/php-${ARCH}-${PHP_VERSION}-${BUILD_TYPE}.tar.gz binaries/
  cache:
    paths:
      - ccache
    key: "php.build.ccache-${ARCH}-${BUILD_TYPE}-${PHP_VERSION}"
  artifacts:
    paths:
      - binaries/
    when: on_success
    expire_in: 2 hours

#region FPM

.build:fpm:
  <<: *shared
  script:
    - cd src
    - EXTRA="--with-pear"
    - if [ "${PHP_VERSION}" == "7.3" ]; then EXTRA="--with-pcre-regex --with-libxml-dir"; fi
    - |
      ./configure \
        --enable-fpm \
        --with-fpm-user=www-data \
        --with-fpm-group=www-data \
        --disable-cgi \
        --prefix=/usr/local \
        --disable-short-tags \
        --build="$(cat /etc/apk/arch)-linux-musl" \
        --host="$(cat /etc/apk/arch)-linux-musl" \
        --with-config-file-path=/usr/local/etc/php \
        --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
        --enable-option-checking=fatal \
        --with-mhash \
        --with-openssl \
        --with-sodium \
        --with-password-argon2 \
        --with-mysqli \
        --with-pdo-mysql \
        --with-zlib \
        --with-zlib-dir \
        --with-curl \
        --enable-exif \
        --enable-calendar \
        --enable-ftp \
        --enable-mbstring \
        --enable-mysqlnd \
        ${EXTRA}
    - make -j4 -i -l V= | awk 'NR%20==0 {print NR,$0}'
    - find -type f -name '*.a' -delete
    - make install
    - cp php.ini-* /usr/local/

build:arm:fpm:7.3:
  extends: .build:fpm
  variables:
    PHP_VERSION: "7.3"
    ARCH: "arm64"
    BUILD_TYPE: fpm
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-aarch64

build:amd:fpm:7.3:
  extends: .build:fpm
  variables:
    BUILD_TYPE: fpm
    PHP_VERSION: "7.3"
    ARCH: "amd64"
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-amd64

build:arm:fpm:7.4:
  extends: .build:fpm
  variables:
    BUILD_TYPE: fpm
    PHP_VERSION: "7.4"
    ARCH: "arm64"
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-aarch64

build:amd:fpm:7.4:
  extends: .build:fpm
  variables:
    BUILD_TYPE: fpm
    PHP_VERSION: "7.4"
    ARCH: "amd64"
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-amd64

# todo: Re-add quai.
.containerize:fpm:
  needs:
    - build:arm:fpm:7.4
    - build:arm:fpm:7.3
    - build:amd:fpm:7.4
    - build:amd:fpm:7.3
    - versions
  stage: containerize
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - FULL_VERSION=$(grep ${PHP_VERSION} versions.txt)
    - printf 'EXPOSE 9000\nCMD ["php-fpm"]' >> Dockerfile
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/fpm" "${FULL_VERSION},${PHP_VERSION}${TAGS}")
    - HUB_TAG_LIST=$(helper "jitesoft/php" "${FULL_VERSION}-fpm,${PHP_VERSION}-fpm${HUB_TAGS}")
    - docker buildx build --platform "linux/amd64,linux/arm64" --progress plain --push ${TAG_LIST} ${HUB_TAG_LIST} --build-arg PHP_MINOR=${PHP_VERSION} --build-arg PHP_VERSION="${FULL_VERSION}" --build-arg BUILD_TYPE="fpm" .
  tags: [ jitesoft, buildx, protected ]


containerize:fpm:7.3:
  extends: .containerize:fpm
  variables:
    PHP_VERSION: "7.3"
    TAGS: ""
    HUB_TAGS: ""

containerize:fpm:7.4:
  extends: .containerize:fpm
  variables:
    PHP_VERSION: "7.4"
    TAGS: ",latest,stable"
    HUB_TAGS: ",latest-fpm,stable-fpm"
#endregion

#region CLI

.build:cli:
  <<: *shared
  script:
    - cd src
    - EXTRA="--with-pear"
    - if [ "${PHP_VERSION}" == "7.3" ]; then EXTRA="--with-pcre-regex"; fi
    - |
      ./configure \
        --prefix=/usr/local \
        --disable-short-tags \
        --build="$(cat /etc/apk/arch)-linux-musl" \
        --host="$(cat /etc/apk/arch)-linux-musl" \
        --with-config-file-path=/usr/local/etc/php \
        --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
        --enable-option-checking=fatal \
        --with-mhash \
        --with-openssl \
        --with-sodium \
        --with-password-argon2 \
        --with-mysqli \
        --with-pdo-mysql \
        --with-zlib \
        --with-curl \
        --with-libedit \
        --enable-calendar \
        --enable-exif \
        --enable-ftp \
        --enable-mbstring \
        --enable-mysqlnd \
        ${EXTRA}
    - make -j4 -i -l V= | awk 'NR%20==0 {print NR,$0}'
    - find -type f -name '*.a' -delete
    - make install
    - cp php.ini-* /usr/local/

build:arm:cli:7.3:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.3"
    ARCH: "arm64"
    BUILD_TYPE: cli
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-aarch64

build:amd:cli:7.3:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.3"
    ARCH: "amd64"
    BUILD_TYPE: cli
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-amd64

build:arm:cli:7.4:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.4"
    ARCH: "arm64"
    BUILD_TYPE: cli
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-aarch64

build:amd:cli:7.4:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.4"
    ARCH: "amd64"
    BUILD_TYPE: cli
    CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  tags:
    - native-amd64

# todo: Re-add quai.
.containerize:cli:
  needs:
    - build:arm:cli:7.4
    - build:arm:cli:7.3
    - build:amd:cli:7.4
    - build:amd:cli:7.3
    - versions
  stage: containerize
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - FULL_VERSION=$(grep ${PHP_VERSION} versions.txt)
    - printf 'CMD ["php", "-a"]' >> Dockerfile
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/cli" "${FULL_VERSION},${PHP_VERSION}${TAGS}")
    - HUB_TAG_LIST=$(helper "jitesoft/php" "${FULL_VERSION},${FULL_VERSION}-cli,${PHP_VERSION},${PHP_VERSION}-cli${HUB_TAGS}")
    - docker buildx build --platform "linux/amd64,linux/arm64" --progress plain --push ${TAG_LIST} ${HUB_TAG_LIST} --build-arg PHP_MINOR=${PHP_VERSION} --build-arg PHP_VERSION="${FULL_VERSION}" --build-arg BUILD_TYPE="cli" .
  tags: [ jitesoft, buildx, protected ]

containerize:cli:7.3:
  extends: .containerize:cli
  variables:
    PHP_VERSION: "7.3"
    TAGS: ""
    HUB_TAGS: ""

containerize:cli:7.4:
  extends: .containerize:cli
  variables:
    PHP_VERSION: "7.4"
    TAGS: ",latest,stable"
    HUB_TAGS: ",latest,stable,latest-cli,stable-cli"
#endregion

.scan:base:
  extends: .container_scanning

scan:fpm:7.4:
  needs:
    - containerize:fpm:7.4
  extends: .scan:base
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/fpm:7.4"
    GIT_STRATEGY: none

scan:cli:7.4:
  needs:
    - containerize:cli:7.4
  extends: .scan:base
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/cli:7.4"
    GIT_STRATEGY: none

scan:fpm:7.3:
  needs:
    - containerize:fpm:7.3
  extends: .scan:base
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/fpm:7.3"
    GIT_STRATEGY: none

scan:cli:7.3:
  needs:
    - containerize:cli:7.3
  extends: .scan:base
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/cli:7.3"
    GIT_STRATEGY: none
