include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - versions
  - prebuild
  - verify
  - build
  - containerize
  - scan
  - notify

versions:
  stage: versions
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
    PHP_MINORS: "3 2"
  before_script:
    - apk add --no-cache grep
  script:
    - |
      for minor in $PHP_MINORS; do
        wget -qO- https://www.php.net/downloads.php | grep -oP "(?<=>php-)([7]\.[${minor}]\.[0-9]{1,2})" | awk 'NR==1{print $1}' >> versions.txt
      done;
  artifacts:
    paths:
      - versions.txt
    expire_in: 3 hours
  tags:
    - jitesoft

gpg:import:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: prebuild
  before_script:
    - apk add --no-cache gnupg
  script:
    - |
      if [ -f keys.out ]; then
        gpg --import keys.out
      fi
    - |
      for key in `cat gpg-keys.txt`; do
        gpg --list-keys ${key} || (gpg --keyserver pgp.mit.edu --recv-keys "${key}" || gpg --keyserver keyserver.pgp.com --recv-keys "${key}" || gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "${key}")
      done
    - gpg --export > keys.out
  cache:
    key: php.gpg.keyring
    paths:
      - keys.out
  artifacts:
    paths:
      - keys.out
    expire_in: 3 hours
  tags:
    - jitesoft

download:
  stage: prebuild
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  variables:
    GIT_STRATEGY: none
  dependencies:
    - versions
  before_script:
    - apk add --no-cache curl
  script:
    - mkdir versions
    - |
      for version in `cat versions.txt`; do
        curl -L https://www.php.net/get/php-${version}.tar.xz/from/this/mirror -o versions/php-${version:0:3}.tar.xz;
        curl -L https://www.php.net/get/php-${version}.tar.xz.asc/from/this/mirror -o versions/php-${version:0:3}.tar.xz.asc;
      done;
    - mkdir aarch64 x86_64
    - |
      for pkg in libedit libargon2 libxml curl openssl; do
        curl -L https://s3.nl-ams.scw.cloud/jitesoft.bin/musl/aarch64/${pkg}.tar.gz.sig -o aarch64/${pkg}.tar.gz.sig
        curl -L https://s3.nl-ams.scw.cloud/jitesoft.bin/musl/aarch64/${pkg}.tar.gz -o aarch64/${pkg}.tar.gz
        curl -L https://s3.nl-ams.scw.cloud/jitesoft.bin/musl/x86_64/${pkg}.tar.gz.sig -o x86_64/${pkg}.tar.gz.sig
        curl -L https://s3.nl-ams.scw.cloud/jitesoft.bin/musl/x86_64/${pkg}.tar.gz -o x86_64/${pkg}.tar.gz
      done
  artifacts:
    paths:
      - versions/*.tar.xz
      - versions/*.tar.xz.asc
      - aarch64/
      - x86_64/
    expire_in: 1 day
  tags:
    - jitesoft

gpg:verify:
  variables:
    GIT_STRATEGY: none
  stage: verify
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  needs:
    - download
    - gpg:import
  before_script:
    - apk add --no-cache gnupg
    - gpg --import keys.out
  script:
    - for i in versions/*.tar.xz ; do gpg --verify ${i}.asc ${i} ; done
    - cd aarch64
    - for pkg in libedit libargon2 libxml curl openssl; do gpg --verify ${pkg}.tar.gz.sig ${pkg}.tar.gz; done
    - cd ../x86_64
    - for pkg in libedit libargon2 libxml curl openssl; do gpg --verify ${pkg}.tar.gz.sig ${pkg}.tar.gz; done
  tags:
    - jitesoft

.cross:build:shared: &shared
  image: registry.gitlab.com/jitesoft/dockerfiles/cross-compile:${ARCH}
  stage: build
  needs:
    - versions
    - gpg:verify
    - download
  before_script:
    - apk add --no-cache re2c bison make xz sed tar file autoconf pkgconf dpkg coreutils wget
    - export CPPFLAGS="${CPPFLAGS} -fstack-protector-strong -fpic -fpie -O2"
    - export LDFLAGS="${LDFLAGS} -L$SYSROOT/lib -L$SYSROOT/usr/lib"
    - export CFLAGS="${CFLAGS} -fstack-protector-strong -fpic -fpie -O2 -I$SYSROOT/include -I$SYSROOT/usr/include -I$SYSROOT/usr/include/libxml2"
    - export PKG_CONFIG_PATH="$SYSROOT/usr/lib/pkgconfig"
    - cp versions/php-${PHP_VERSION}.tar.xz php.tar.xz
    - mkdir src
    - tar -Jxhf php.tar.xz -C src/ --strip-components=1
    - if [ ! -f /lib/ld-musl-${GNU_ARCH}.so.1 ]; then ln -fs ${SYSROOT}/lib/ld-musl-${GNU_ARCH}.so.1 /lib/ld-musl-${GNU_ARCH}.so.1; fi # Move to base image.
    - addgroup -g 82 -S www-data && adduser -u 82 -D -S -G www-data www-data
  after_script:
    - if [ ! -f src/config.log ]; then touch src/config.log; fi
    - mv src/config.log .
  artifacts:
    paths:
      - php-${ARCH}.tar.gz
      - config.log
    when: always
    expire_in: 5 days

#region FPM

.build:fpm:
  <<: *shared
  script:
    - for pkg in libedit libxml libargon2; do tar -xzhf ${GNU_ARCH}/${pkg}.tar.gz -C ${SYSROOT}/usr; done
    - cd src
    - EXTRA_APK_ARGS="--no-scripts"
    - if [ "${GNU_ARCH}" == "$(cat /etc/apk/arch)" ]; then EXTRA_APK_ARGS=""; fi
    - |
      apk add --no-cache \
        --repositories-file /etc/apk/repositories \
        --keys-dir /etc/apk/keys \
        --initdb \
        --no-scripts \
        --allow-untrusted \
        --root ${SYSROOT} \
        --arch ${GNU_ARCH} \
        --virtual .build-deps coreutils libedit-dev curl-dev openssl-dev libsodium-dev sqlite-dev re2c bison || echo "Install errors are okay, as only libs are needed!"
    - |
      ./configure \
        --enable-fpm \
        --with-fpm-user=www-data \
        --with-fpm-group=www-data \
        --disable-cgi \
        --with-libdir="$SYSROOT/lib" \
        --prefix=/usr/local \
        --disable-short-tags \
        --build="x86_64-linux-musl" \
        --host="${GNU_TRIPLET}" \
        --with-config-file-path=/usr/local/etc/php \
        --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
        --enable-option-checking=fatal \
        --with-mhash \
        --with-pcre-regex \
        --with-openssl \
        --with-openssl-dir \
        --with-sodium=shared \
        --with-password-argon2=${SYSROOT}/usr \
        --with-libxml-dir=${SYSROOT}/usr \
        --with-mysqli \
        --with-zlib \
        --with-zlib-dir=${SYSROOT}/usr \
        --with-curl \
        --enable-calendar \
        --enable-ftp \
        --enable-mbstring \
        --enable-mysqlnd
     - make -j4 -i -l V= | awk 'NR%20==0 {print NR,$0}'
     - find -type f -name '*.a' -delete
     - make install
     - cp src/php.ini-* /usr/local/
     - $(cd /usr/local && tar -czf /tmp/php-${ARCH}.tar.gz *)
     - mv /tmp/php-${ARCH}.tar.gz .

build:arm:fpm:7.3:
  extends: .build:fpm
  variables:
    PHP_VERSION: "7.3"
    ARCH: "arm64"

build:amd:fpm:7.3:
  extends: .build:fpm
  variables:
    PHP_VERSION: "7.3"
    ARCH: "amd64"

build:arm:fpm:7.2:
  extends: .build:fpm
  variables:
    PHP_VERSION: "7.2"
    ARCH: "arm64"

build:amd:fpm:7.2:
  extends: .build:fpm
  variables:
    PHP_VERSION: "7.2"
    ARCH: "amd64"

.containerize:fpm:
  stage: containerize
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - FULL_VERSION=$(grep ${PHP_VERSION} versions.txt)
    - printf 'EXPOSE 9000\nCMD ["php-fpm"]' >> Dockerfile
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/fpm" "${FULL_VERSION},${PHP_VERSION}{TAGS}")
    - docker buildx build --platform "linux/amd64,linux/arm64" --cache-from=${CI_REGISTRY_IMAGE}/cache:${PHP_VERSION}-fpm --cache-to=${CI_REGISTRY_IMAGE}/cache:${PHP_VERSION}-fpm --progress plain --push ${TAG_LIST} --build-arg PHP_VERSION="${FULL_VERSION}" --build-arg BUILD_TYPE="fpm" .
  tags: [ jitesoft, buildx, amd64, arm64 ]

containerize:fpm:7.3:
  extends: .containerize:fpm
  needs:
    - versions
    - build:arm:fpm:7.3
    - build:amd:fpm:7.3
  variables:
    PHP_VERSION: "7.3"
    V_REGEX: '7\.3'
    TAGS: ",latest,stable"

containerize:fpm:7.2:
  extends: .containerize:fpm
  needs:
    - versions
    - build:arm:fpm:7.2
    - build:amd:fpm:7.2
  variables:
    PHP_VERSION: "7.2"
    V_REGEX: '7\.2'
    TAGS: ""

#endregion

#region CLI

.build:cli:
  <<: *shared
  script:
    - for pkg in libedit libxml libargon2; do tar -xzhf ${GNU_ARCH}/${pkg}.tar.gz -C ${SYSROOT}/usr; done
    - cd src
    - EXTRA_APK_ARGS="--no-scripts"
    - if [ "${GNU_ARCH}" == "$(cat /etc/apk/arch)" ]; then EXTRA_APK_ARGS=""; fi
    - |
      apk add --no-cache \
        --repositories-file /etc/apk/repositories \
        --keys-dir /etc/apk/keys \
        --initdb \
        --allow-untrusted \
        --root ${SYSROOT} \
        --arch ${GNU_ARCH} \
        --virtual .build-deps coreutils curl-dev libedit-dev curl-dev openssl-dev libsodium-dev sqlite-dev re2c bison || echo "Install errors are okay, as only libs are needed!"
    - |
      ./configure \
        --with-libdir="$SYSROOT/lib" \
        --prefix=/usr/local \
        --disable-short-tags \
        --build="x86_64-linux-musl" \
        --host="${GNU_TRIPLET}" \
        --with-config-file-path=/usr/local/etc/php \
        --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
        --enable-option-checking=fatal \
        --with-mhash \
        --with-pcre-regex \
        --with-openssl \
        --with-openssl-dir=${SYSROOT}/usr \
        --with-sodium=shared \
        --with-password-argon2=${SYSROOT}/usr \
        --with-libxml-dir=${SYSROOT}/usr \
        --with-mysqli \
        --with-zlib \
        --with-zlib-dir=${SYSROOT}/usr \
        --with-curl \
        --with-libedit=${SYSROOT}/usr \
        --enable-calendar \
        --enable-ftp \
        --enable-mbstring \
        --enable-mysqlnd
    - make -j4 -i -l V= | awk 'NR%20==0 {print NR,$0}'
    - find -type f -name '*.a' -delete
    - make install
    - cp src/php.ini-* /usr/local/
    - $(cd /usr/local && tar -czf /tmp/php-${ARCH}.tar.gz *)
    - mv /tmp/php-${ARCH}.tar.gz .

build:arm:cli:7.3:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.3"
    ARCH: "arm64"

build:amd:cli:7.3:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.3"
    ARCH: "amd64"

build:arm:cli:7.2:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.2"
    ARCH: "arm64"

build:amd:cli:7.2:
  extends: .build:cli
  variables:
    PHP_VERSION: "7.2"
    ARCH: "amd64"

.containerize:cli:
  stage: containerize
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - FULL_VERSION=$(grep ${PHP_VERSION} versions.txt)
    - printf 'CMD ["php", "-a"]' >> Dockerfile
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/cli" "${FULL_VERSION},${PHP_VERSION}{TAGS}")
    - docker buildx build --platform "linux/amd64,linux/arm64" --cache-from=${CI_REGISTRY_IMAGE}/cache:${PHP_VERSION}-cli --cache-to=${CI_REGISTRY_IMAGE}/cache:${PHP_VERSION}-cli --progress plain --push ${TAG_LIST} --build-arg PHP_VERSION="${FULL_VERSION}" --build-arg BUILD_TYPE="cli" .
  tags: [ jitesoft, buildx, amd64, arm64 ]

containerize:cli:7.3:
  extends: .containerize:cli
  needs:
    - versions
    - build:arm:cli:7.3
    - build:amd:cli:7.3
  variables:
    PHP_VERSION: "7.3"
    TAGS: ",latest,stable"
    V_REGEX: '7\.3'

containerize:cli:7.2:
  needs:
    - versions
    - build:arm:cli:7.2
    - build:amd:cli:7.2
  extends: .containerize:cli
  variables:
    PHP_VERSION: "7.2"
    V_REGEX: '7\.2'
    TAGS: ""

#endregion

scan:fpm:7.2:
  needs:
    - containerize:fpm:7.2
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/fpm:7.2"
    GIT_STRATEGY: none

scan:cli:7.2:
  needs:
    - containerize:cli:7.2
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/cli:7.2"
    GIT_STRATEGY: none

scan:fpm:7.3:
  needs:
    - containerize:fpm:7.3
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/fpm:7.3"
    GIT_STRATEGY: none

scan:cli:7.3:
  needs:
    - containerize:cli:7.3
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/cli:7.3"
    GIT_STRATEGY: none

.trigger_build:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: notify
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${COMPOSER_TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4048644/trigger/pipeline"
    - "curl -X POST -F token=${PHP_FPM_TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/4048646/trigger/pipeline"
  variables:
    GIT_STRATEGY: none
