#!/bin/sh
usage() {
    echo "Usage:
Manage php extensions.
  Commands:
    source    - Manage packing and unpacking of the php source code.
    install   - Install extensions.
    configure - Configure extensions.
    enable    - Enable already installed extensions."
}
COMMAND=${1}
shift

case ${COMMAND} in
    source)
        docker-php-ext-source $@
        ;;
    install)
        docker-php-ext-install $@
        ;;
    configure)
        docker-php-ext-configure $@
        ;;
    enable)
        docker-php-source $@
        ;;
    *)
        usage
        exit 1
    ;;
esac
